# Generated by Django 5.1.7 on 2025-04-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
