# Generated by Django 5.1.7 on 2025-04-16 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/'),
        ),
        migrations.AddField(
            model_name='message',
            name='exchange_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.exchangeschedule'),
        ),
    ]
