# Generated by Django 5.1.7 on 2025-04-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_message_attachments_message_exchange_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
